### ISSUE TITLE
Zoneinfo directory not created on build 2021a=h7f98852_1

### ISSUE THREAD

**Issue by mstabrin** [conda-forge/tzcode-feedstock#13]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
TL;DR: There are no folders created related to zoneinfo in `$PREFIX/share`

Hello tzcode Team,
I moved from postgresql installed from channel anaconda to the installation available on conda-forge, which uses the tzcode package for timezone information.
Starting the DB I get an error saying that the $PREFIX/share/zoneinfo folder does not exist and indeed, there is no such folder present and it seems to be due to a problem in the latest tzcode 2021 version build h7f98852_1.

```
$ conda install tzcode=2021a=h7f98852_1 --force-reinstall -c conda-forge
$ ls -l $CONDA_PREFIX/share
drwxr-xr-x 2 markus markus 4096  7. Jul 08:32 info
drwxr-xr-x 3 markus markus 4096  7. Jul 08:32 licenses

$ conda install tzcode=2021a=h7f98852_0 --force-reinstall -c conda-forge
$ ls -l $CONDA_PREFIX/share
drwxr-xr-x  2 markus markus 4096  7. Jul 08:32 info
drwxr-xr-x  3 markus markus 4096  7. Jul 08:32 licenses
drwxr-xr-x  5 markus markus 4096  7. Jul 08:41 man
drwxr-xr-x 18 markus markus 4096  7. Jul 08:41 zoneinfo
drwxr-xr-x 18 markus markus 4096  7. Jul 08:41 zoneinfo-leaps
lrwxrwxrwx  1 markus markus    8  7. Jul 08:41 zoneinfo-posix -> zoneinfo
```
I will downgrade to the first build of the year now, but wanted to bring it to your attention :)

Best,
Markus

<br/>
Environment h7f98852_1 (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/self_installed_programs/anaconda3/envs/tzcode:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
tzcode                    2021a                h7f98852_1    conda-forge

```
</details>

Environment h7f98852_0 (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/self_installed_programs/anaconda3/envs/tzcode:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
tzcode                    2021a                h7f98852_0    conda-forge


```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : tzcode
    active env location : /opt/self_installed_programs/anaconda3/envs/tzcode
            shell level : 2
       user config file : /home/markus/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : 3.10.7
         python version : 3.6.10.final.0
       virtual packages : __glibc=2.33=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/self_installed_programs/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/self_installed_programs/anaconda3/pkgs
                          /home/markus/.conda/pkgs
       envs directories : /opt/self_installed_programs/anaconda3/envs
                          /home/markus/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.6.10 Linux/5.12.9-arch1-1 arch/rolling glibc/2.33
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by xylar** [comment]
@mstabrin, there is a separate package for that info: https://github.com/conda-forge/tzdata-feedstock.  Including that directory in `tzcode` was causing a very large number of conflicts when both `tzcode` and `tzdata` are installed.  Please try to install `tzdata` as well and let us know if that solves the issue for you.

**Comment by mstabrin** [comment]
@xylar Thank you that seemed to have worked!

I am dealing with an older version of postgresql right now, which did not have that separation included in their dependencies.
Even knowing the issue now, I am still unable to find information about the separation or even the tzdata package in general without explicitly including tzdata in the search.

Maybe it would be helpful to put some information about it in the anaconda.org package description and/or the Readme of both feedstocks :)

Thanks again!
Best,
Markus

**Comment by xylar** [comment]
> Maybe it would be helpful to put some information about it in the anaconda.org package description and/or the Readme of both feedstocks :)

@ocefpaf, is there a good place for this information to go?

**Comment by xylar** [comment]
Answering my own question, editing the package description will take care of both readme files as well.

**Comment by ocefpaf** [comment]
Thanks for taking care of that @xylar!
